'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Usuario() As Integer
            Get
                Return CType(Me("Usuario"),Integer)
            End Get
            Set
                Me("Usuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IGV() As Decimal
            Get
                Return CType(Me("IGV"),Decimal)
            End Get
            Set
                Me("IGV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieCompraFactura() As String
            Get
                Return CType(Me("UltimoSerieCompraFactura"),String)
            End Get
            Set
                Me("UltimoSerieCompraFactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieVentaBoleta() As String
            Get
                Return CType(Me("UltimoSerieVentaBoleta"),String)
            End Get
            Set
                Me("UltimoSerieVentaBoleta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieCompraBoleta() As String
            Get
                Return CType(Me("UltimoSerieCompraBoleta"),String)
            End Get
            Set
                Me("UltimoSerieCompraBoleta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UltimoTipoUsadoCompra() As Integer
            Get
                Return CType(Me("UltimoTipoUsadoCompra"),Integer)
            End Get
            Set
                Me("UltimoTipoUsadoCompra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieVentaFactura() As String
            Get
                Return CType(Me("UltimoSerieVentaFactura"),String)
            End Get
            Set
                Me("UltimoSerieVentaFactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UltimaFechaCompra() As Date
            Get
                Return CType(Me("UltimaFechaCompra"),Date)
            End Get
            Set
                Me("UltimaFechaCompra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UltimaFechaVentaBoleta() As Date
            Get
                Return CType(Me("UltimaFechaVentaBoleta"),Date)
            End Get
            Set
                Me("UltimaFechaVentaBoleta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UltimaFechaVentaFactura() As Date
            Get
                Return CType(Me("UltimaFechaVentaFactura"),Date)
            End Get
            Set
                Me("UltimaFechaVentaFactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActualizarPrecioVenta() As Boolean
            Get
                Return CType(Me("ActualizarPrecioVenta"),Boolean)
            End Get
            Set
                Me("ActualizarPrecioVenta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActualizaPrecioCompra() As Boolean
            Get
                Return CType(Me("ActualizaPrecioCompra"),Boolean)
            End Get
            Set
                Me("ActualizaPrecioCompra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IdUltimoUsuario() As Integer
            Get
                Return CType(Me("IdUltimoUsuario"),Integer)
            End Get
            Set
                Me("IdUltimoUsuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MostrarControlesAvanzados() As Boolean
            Get
                Return CType(Me("MostrarControlesAvanzados"),Boolean)
            End Get
            Set
                Me("MostrarControlesAvanzados") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NombreUsuario() As String
            Get
                Return CType(Me("NombreUsuario"),String)
            End Get
            Set
                Me("NombreUsuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimaSerieProforma() As String
            Get
                Return CType(Me("UltimaSerieProforma"),String)
            End Get
            Set
                Me("UltimaSerieProforma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieGarantiaFactura() As String
            Get
                Return CType(Me("UltimoSerieGarantiaFactura"),String)
            End Get
            Set
                Me("UltimoSerieGarantiaFactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieGarantiaBoleta() As String
            Get
                Return CType(Me("UltimoSerieGarantiaBoleta"),String)
            End Get
            Set
                Me("UltimoSerieGarantiaBoleta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieProformaFactura() As String
            Get
                Return CType(Me("UltimoSerieProformaFactura"),String)
            End Get
            Set
                Me("UltimoSerieProformaFactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimoSerieProformaBoleta() As String
            Get
                Return CType(Me("UltimoSerieProformaBoleta"),String)
            End Get
            Set
                Me("UltimoSerieProformaBoleta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UltimaFechaProforma() As Date
            Get
                Return CType(Me("UltimaFechaProforma"),Date)
            End Get
            Set
                Me("UltimaFechaProforma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UltimaFechaGarantia() As Date
            Get
                Return CType(Me("UltimaFechaGarantia"),Date)
            End Get
            Set
                Me("UltimaFechaGarantia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UltimaSerieGarantia() As String
            Get
                Return CType(Me("UltimaSerieGarantia"),String)
            End Get
            Set
                Me("UltimaSerieGarantia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ValorDolar() As Decimal
            Get
                Return CType(Me("ValorDolar"),Decimal)
            End Get
            Set
                Me("ValorDolar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UltimoPeriodoVentaSel() As Integer
            Get
                Return CType(Me("UltimoPeriodoVentaSel"),Integer)
            End Get
            Set
                Me("UltimoPeriodoVentaSel") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SistemaServox2015.My.MySettings
            Get
                Return Global.SistemaServox2015.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
